const listOfStudents10B = () => {
  const list = [
    {
      name: 'Эдди Шор',
      dateOfBirth: '13.03.1955',
      russian: 4,
      math: 4,
      geometry: 4,
      physics: 4,
      chemistry: 4,
      biology: 4,
      socialScience: 4,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    },
    {
      name: 'Бобби Ор',
      dateOfBirth: '24.07.1960',
      russian: 5,
      math: 5,
      geometry: 5,
      physics: 5,
      chemistry: 5,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    },
    {
      name: 'Горди Хоу',
      dateOfBirth: '13.12.1991',
      russian: 4,
      math: 4,
      geometry: 4,
      physics: 4,
      chemistry: 4,
      biology: 4,
      socialScience: 4,
      rights: 4,
      history: 4,
      english: 4,
      german: 4,
      art: 4,
      work: 4,
      religion: 4,
      training: 4,
      sambo: 4,
      judo: 4,
      shooting: 4,
      sledding: 4
    },
    {
      name: 'Фил Эспозито',
      dateOfBirth: '17.09.1985',
      russian: 5,
      math: 5,
      geometry: 5,
      physics: 5,
      chemistry: 5,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    },
    {
      name: 'Анри Ришар',
      dateOfBirth: '23.07.1991',
      russian: 5,
      math: 5,
      geometry: 5,
      physics: 5,
      chemistry: 5,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    },
    {
      name: 'Сил Эппс',
      dateOfBirth: '02.01.1963',
      russian: 5,
      math: 5,
      geometry: 5,
      physics: 5,
      chemistry: 5,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    },
    {
      name: 'Яромир Ягр',
      dateOfBirth: '26.04.1997',
      russian: 3,
      math: 3,
      geometry: 3,
      physics: 3,
      chemistry: 3,
      biology: 3,
      socialScience: 3,
      rights: 3,
      history: 3,
      english: 5,
      german: 3,
      art: 3,
      work: 5,
      religion: 3,
      training: 5,
      sambo: 3,
      judo: 5,
      shooting: 5,
      sledding: 3
    },
    {
      name: 'Кинг Клэнси',
      dateOfBirth: '15.04.1983',
      russian: 2,
      math: 2,
      geometry: 2,
      physics: 2,
      chemistry: 2,
      biology: 2,
      socialScience: 2,
      rights: 2,
      history: 2,
      english: 2,
      german: 2,
      art: 2,
      work: 2,
      religion: 2,
      training: 2,
      sambo: 2,
      judo: 2,
      shooting: 2,
      sledding: 2
    },
    {
      name: 'Билли Смит',
      dateOfBirth: '31.07.1986',
      russian: 5,
      math: 5,
      geometry: 5,
      physics: 5,
      chemistry: 5,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    },
    {
      name: 'Бэйб Дай',
      dateOfBirth: '17.07.1993',
      russian: 5,
      math: 5,
      geometry: 5,
      physics: 5,
      chemistry: 5,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    },
    {
      name: 'Боб Гейни',
      dateOfBirth: '25.07.1994',
      russian: 5,
      math: 5,
      geometry: 5,
      physics: 5,
      chemistry: 5,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    },
    {
      name: 'Джо Примо',
      dateOfBirth: '26.01.1961',
      russian: 5,
      math: 5,
      geometry: 5,
      physics: 5,
      chemistry: 5,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    },
    {
      name: 'Доминик Гашек',
      dateOfBirth: '28.02.1992',
      russian: 2,
      math: 2,
      geometry: 2,
      physics: 2,
      chemistry: 2,
      biology: 2,
      socialScience: 2,
      rights: 2,
      history: 2,
      english: 3,
      german: 3,
      art: 3,
      work: 3,
      religion: 2,
      training: 2,
      sambo: 3,
      judo: 3,
      shooting: 3,
      sledding: 3
    },
    {
      name: 'Иван Курнуайе',
      dateOfBirth: '14.01.1948',
      russian: 5,
      math: 5,
      geometry: 5,
      physics: 5,
      chemistry: 5,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    },
    {
      name: 'Билл Гадсби',
      dateOfBirth: '25.04.1972',
      russian: 5,
      math: 5,
      geometry: 5,
      physics: 5,
      chemistry: 5,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    },
    {
      name: 'Фрэнк Нэйбор',
      dateOfBirth: '20.07.1978',
      russian: 4,
      math: 4,
      geometry: 4,
      physics: 4,
      chemistry: 4,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 4,
      art: 4,
      work: 4,
      religion: 5,
      training: 4,
      sambo: 4,
      judo: 5,
      shooting: 5,
      sledding: 4
    },
    {
      name: 'Дэррил Ситтер',
      dateOfBirth: '07.08.1987',
      russian: 5,
      math: 5,
      geometry: 5,
      physics: 5,
      chemistry: 5,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    },
    {
      name: 'Лорн Шабо',
      dateOfBirth: '22.02.1997',
      russian: 3,
      math: 3,
      geometry: 3,
      physics: 3,
      chemistry: 3,
      biology: 3,
      socialScience: 3,
      rights: 3,
      history: 3,
      english: 3,
      german: 3,
      art: 3,
      work: 3,
      religion: 3,
      training: 3,
      sambo: 3,
      judo: 3,
      shooting: 3,
      sledding: 3
    },
    {
      name: 'Норм Ульман',
      dateOfBirth: '31.03.1971',
      russian: 5,
      math: 5,
      geometry: 5,
      physics: 5,
      chemistry: 5,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    }
  ]

  return list
}

export default listOfStudents10B
