const listOfStudents10A = () => {
  const list = [
    {
      name: 'Быков В.А.',
      dateOfBirth: '24.07.1960',
      russian: 5,
      math: 5,
      geometry: 5,
      physics: 5,
      chemistry: 5,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    },
    {
      name: 'Билялетдиинов З.Х.',
      dateOfBirth: '13.03.1955',
      russian: 4,
      math: 4,
      geometry: 4,
      physics: 4,
      chemistry: 4,
      biology: 4,
      socialScience: 4,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    },
    {
      name: 'Овечкин А.А.',
      dateOfBirth: '17.09.1985',
      russian: 5,
      math: 5,
      geometry: 5,
      physics: 5,
      chemistry: 5,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    },
    {
      name: 'Орлов А.А.',
      dateOfBirth: '23.07.1991',
      russian: 5,
      math: 5,
      geometry: 5,
      physics: 5,
      chemistry: 5,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    },
    {
      name: 'Тарасенко А.А.',
      dateOfBirth: '13.12.1991',
      russian: 4,
      math: 4,
      geometry: 4,
      physics: 4,
      chemistry: 4,
      biology: 4,
      socialScience: 4,
      rights: 4,
      history: 4,
      english: 4,
      german: 4,
      art: 4,
      work: 4,
      religion: 4,
      training: 4,
      sambo: 4,
      judo: 4,
      shooting: 4,
      sledding: 4
    },
    {
      name: 'Капризов К.А.',
      dateOfBirth: '26.04.1997',
      russian: 3,
      math: 3,
      geometry: 3,
      physics: 3,
      chemistry: 3,
      biology: 3,
      socialScience: 3,
      rights: 3,
      history: 3,
      english: 5,
      german: 3,
      art: 3,
      work: 5,
      religion: 3,
      training: 5,
      sambo: 3,
      judo: 5,
      shooting: 5,
      sledding: 3
    },
    {
      name: 'Знарок О.А.',
      dateOfBirth: '02.01.1963',
      russian: 5,
      math: 5,
      geometry: 5,
      physics: 5,
      chemistry: 5,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    },
    {
      name: 'Ковальчук С.А.',
      dateOfBirth: '15.04.1983',
      russian: 2,
      math: 2,
      geometry: 2,
      physics: 2,
      chemistry: 2,
      biology: 2,
      socialScience: 2,
      rights: 2,
      history: 2,
      english: 2,
      german: 2,
      art: 2,
      work: 2,
      religion: 2,
      training: 2,
      sambo: 2,
      judo: 2,
      shooting: 2,
      sledding: 2
    },
    {
      name: 'Малкин Е.А.',
      dateOfBirth: '31.07.1986',
      russian: 5,
      math: 5,
      geometry: 5,
      physics: 5,
      chemistry: 5,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    },
    {
      name: 'Телегин И.А.',
      dateOfBirth: '28.02.1992',
      russian: 2,
      math: 2,
      geometry: 2,
      physics: 2,
      chemistry: 2,
      biology: 2,
      socialScience: 2,
      rights: 2,
      history: 2,
      english: 3,
      german: 3,
      art: 3,
      work: 3,
      religion: 2,
      training: 2,
      sambo: 3,
      judo: 3,
      shooting: 3,
      sledding: 3
    },
    {
      name: 'Кучеров Н.А.',
      dateOfBirth: '17.07.1993',
      russian: 5,
      math: 5,
      geometry: 5,
      physics: 5,
      chemistry: 5,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    },
    {
      name: 'Василевский А.А.',
      dateOfBirth: '25.07.1994',
      russian: 5,
      math: 5,
      geometry: 5,
      physics: 5,
      chemistry: 5,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    },
    {
      name: 'Гретцки У.А.',
      dateOfBirth: '26.01.1961',
      russian: 5,
      math: 5,
      geometry: 5,
      physics: 5,
      chemistry: 5,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    },
    {
      name: 'Третьяк В.А.',
      dateOfBirth: '25.04.1972',
      russian: 5,
      math: 5,
      geometry: 5,
      physics: 5,
      chemistry: 5,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    },
    {
      name: 'Харламов В.А.',
      dateOfBirth: '14.01.1948',
      russian: 5,
      math: 5,
      geometry: 5,
      physics: 5,
      chemistry: 5,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    },
    {
      name: 'Дацюк П.А.',
      dateOfBirth: '20.07.1978',
      russian: 4,
      math: 4,
      geometry: 4,
      physics: 4,
      chemistry: 4,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 4,
      art: 4,
      work: 4,
      religion: 5,
      training: 4,
      sambo: 4,
      judo: 5,
      shooting: 5,
      sledding: 4
    },
    {
      name: 'Кросби С.А.',
      dateOfBirth: '07.08.1987',
      russian: 5,
      math: 5,
      geometry: 5,
      physics: 5,
      chemistry: 5,
      biology: 5,
      socialScience: 5,
      rights: 5,
      history: 5,
      english: 5,
      german: 5,
      art: 5,
      work: 5,
      religion: 5,
      training: 5,
      sambo: 5,
      judo: 5,
      shooting: 5,
      sledding: 5
    },
    {
      name: 'Буре П.А.',
      dateOfBirth: '31.03.1971',
      russian: 10,
      math: 10,
      geometry: 10,
      physics: 10,
      chemistry: 10,
      biology: 10,
      socialScience: 10,
      rights: 10,
      history: 10,
      english: 10,
      german: 10,
      art: 10,
      work: 10,
      religion: 10,
      training: 10,
      sambo: 10,
      judo: 10,
      shooting: 10,
      sledding: 10
    },
    {
      name: 'Самснов А.А.',
      dateOfBirth: '22.02.1997',
      russian: 3,
      math: 3,
      geometry: 3,
      physics: 3,
      chemistry: 3,
      biology: 3,
      socialScience: 3,
      rights: 3,
      history: 3,
      english: 3,
      german: 3,
      art: 3,
      work: 3,
      religion: 3,
      training: 3,
      sambo: 3,
      judo: 3,
      shooting: 3,
      sledding: 3
    }
  ]

  return list
}

export default listOfStudents10A
