<template>
  <v-container>
    <v-card>
      <v-card-title>
        Промежуточные оценки за полугодие
        <v-spacer></v-spacer>
        <v-text-field
          v-model="search"
          append-icon="mdi-magnify"
          label="Поиск"
          single-line
          hide-details
        ></v-text-field>
      </v-card-title>
      <v-data-table
        height="80vh"
        fixed-header
        hide-default-footer
        :headers="headers"
        :items="students"
        :search="search"
        :items-per-page="150"
      >
      </v-data-table>
    </v-card>
  </v-container>
</template>

<script>
export default {
  data () {
    return {
      search: '',
      headers: [
        {
          text: 'ФИО студента',
          align: 'start',
          fixed: true,
          value: 'name',
          width: '180px'
        },
        { text: 'Дата рождения', align: 'start', value: 'dateOfBirth', width: '145px', fixed: true },
        { text: 'Русский язык', align: 'start', value: 'russian', width: 130 },
        { text: 'Математика', align: 'start', value: 'math', width: 125 },
        { text: 'Геометрия', align: 'start', value: 'geometry', width: 115 },
        { text: 'Физика', align: 'start', value: 'physics', width: 95 },
        { text: 'Химия', align: 'start', value: 'chemistry', width: 90 },
        { text: 'Биология', align: 'start', value: 'biology', width: 110 },
        { text: 'Обществ-е', align: 'start', value: 'socialScience', width: 115 },
        { text: 'Право', align: 'start', value: 'rights', width: 90 },
        { text: 'История', align: 'start', value: 'history', width: 100 },
        { text: 'Английский язык', align: 'start', value: 'english', width: 150 },
        { text: 'Немецкий язык', align: 'start', value: 'german', width: 145 },
        { text: 'ИЗО', align: 'start', value: 'art', width: 80 },
        { text: 'Труд', align: 'start', value: 'work', width: 100 },
        { text: 'Религии мира', align: 'start', value: 'religion', width: 130 },
        { text: 'Физ-ра', align: 'start', value: 'training', width: 100 },
        { text: 'Самбо', align: 'start', value: 'sambo', width: 90 },
        { text: 'Дзюдо', align: 'start', value: 'judo', width: 90 },
        { text: 'Стрельба', align: 'start', value: 'shooting', width: 110 },
        { text: 'Езда на санках', align: 'start', value: 'sledding', width: 135 }
      ],
      students: [
        {
          name: 'Быков В.А.',
          russian: 5,
          math: 5,
          geometry: 5,
          physics: 5,
          chemistry: 5,
          biology: 5,
          socialScience: 5,
          rights: 5,
          history: 5,
          english: 5,
          german: 5,
          art: 5,
          work: 5,
          religion: 5,
          training: 5,
          sambo: 5,
          judo: 5,
          shooting: 5,
          sledding: 5
        },
        {
          name: 'Билялетдиинов З.Х.',
          russian: 4,
          math: 4,
          geometry: 4,
          physics: 4,
          chemistry: 4,
          biology: 4,
          socialScience: 4,
          rights: 5,
          history: 5,
          english: 5,
          german: 5,
          art: 5,
          work: 5,
          religion: 5,
          training: 5,
          sambo: 5,
          judo: 5,
          shooting: 5,
          sledding: 5
        },
        {
          name: 'Овечкин А.А.',
          russian: 5,
          math: 5,
          geometry: 5,
          physics: 5,
          chemistry: 5,
          biology: 5,
          socialScience: 5,
          rights: 5,
          history: 5,
          english: 5,
          german: 5,
          art: 5,
          work: 5,
          religion: 5,
          training: 5,
          sambo: 5,
          judo: 5,
          shooting: 5,
          sledding: 5
        },
        {
          name: 'Орлов А.А.',
          russian: 5,
          math: 5,
          geometry: 5,
          physics: 5,
          chemistry: 5,
          biology: 5,
          socialScience: 5,
          rights: 5,
          history: 5,
          english: 5,
          german: 5,
          art: 5,
          work: 5,
          religion: 5,
          training: 5,
          sambo: 5,
          judo: 5,
          shooting: 5,
          sledding: 5
        },
        {
          name: 'Тарасенко А.А.',
          russian: 4,
          math: 4,
          geometry: 4,
          physics: 4,
          chemistry: 4,
          biology: 4,
          socialScience: 4,
          rights: 4,
          history: 4,
          english: 4,
          german: 4,
          art: 4,
          work: 4,
          religion: 4,
          training: 4,
          sambo: 4,
          judo: 4,
          shooting: 4,
          sledding: 4
        },
        {
          name: 'Капризов К.А.',
          russian: 3,
          math: 3,
          geometry: 3,
          physics: 3,
          chemistry: 3,
          biology: 3,
          socialScience: 3,
          rights: 3,
          history: 3,
          english: 5,
          german: 3,
          art: 3,
          work: 5,
          religion: 3,
          training: 5,
          sambo: 3,
          judo: 5,
          shooting: 5,
          sledding: 3
        },
        {
          name: 'Знарок О.А.',
          russian: 5,
          math: 5,
          geometry: 5,
          physics: 5,
          chemistry: 5,
          biology: 5,
          socialScience: 5,
          rights: 5,
          history: 5,
          english: 5,
          german: 5,
          art: 5,
          work: 5,
          religion: 5,
          training: 5,
          sambo: 5,
          judo: 5,
          shooting: 5,
          sledding: 5
        },
        {
          name: 'Ковальчук С.А.',
          russian: 2,
          math: 2,
          geometry: 2,
          physics: 2,
          chemistry: 2,
          biology: 2,
          socialScience: 2,
          rights: 2,
          history: 2,
          english: 2,
          german: 2,
          art: 2,
          work: 2,
          religion: 2,
          training: 2,
          sambo: 2,
          judo: 2,
          shooting: 2,
          sledding: 2
        },
        {
          name: 'Малкин Е.А.',
          russian: 5,
          math: 5,
          geometry: 5,
          physics: 5,
          chemistry: 5,
          biology: 5,
          socialScience: 5,
          rights: 5,
          history: 5,
          english: 5,
          german: 5,
          art: 5,
          work: 5,
          religion: 5,
          training: 5,
          sambo: 5,
          judo: 5,
          shooting: 5,
          sledding: 5
        },
        {
          name: 'Телегин И.А.',
          russian: 2,
          math: 2,
          geometry: 2,
          physics: 2,
          chemistry: 2,
          biology: 2,
          socialScience: 2,
          rights: 2,
          history: 2,
          english: 3,
          german: 3,
          art: 3,
          work: 3,
          religion: 2,
          training: 2,
          sambo: 3,
          judo: 3,
          shooting: 3,
          sledding: 3
        },
        {
          name: 'Кучеров Н.А.',
          russian: 5,
          math: 5,
          geometry: 5,
          physics: 5,
          chemistry: 5,
          biology: 5,
          socialScience: 5,
          rights: 5,
          history: 5,
          english: 5,
          german: 5,
          art: 5,
          work: 5,
          religion: 5,
          training: 5,
          sambo: 5,
          judo: 5,
          shooting: 5,
          sledding: 5
        },
        {
          name: 'Василевский А.А.',
          russian: 5,
          math: 5,
          geometry: 5,
          physics: 5,
          chemistry: 5,
          biology: 5,
          socialScience: 5,
          rights: 5,
          history: 5,
          english: 5,
          german: 5,
          art: 5,
          work: 5,
          religion: 5,
          training: 5,
          sambo: 5,
          judo: 5,
          shooting: 5,
          sledding: 5
        },
        {
          name: 'Грецки У.А.',
          russian: 5,
          math: 5,
          geometry: 5,
          physics: 5,
          chemistry: 5,
          biology: 5,
          socialScience: 5,
          rights: 5,
          history: 5,
          english: 5,
          german: 5,
          art: 5,
          work: 5,
          religion: 5,
          training: 5,
          sambo: 5,
          judo: 5,
          shooting: 5,
          sledding: 5
        },
        {
          name: 'Третьяк В.А.',
          russian: 5,
          math: 5,
          geometry: 5,
          physics: 5,
          chemistry: 5,
          biology: 5,
          socialScience: 5,
          rights: 5,
          history: 5,
          english: 5,
          german: 5,
          art: 5,
          work: 5,
          religion: 5,
          training: 5,
          sambo: 5,
          judo: 5,
          shooting: 5,
          sledding: 5
        },
        {
          name: 'Харламов В.А.',
          russian: 5,
          math: 5,
          geometry: 5,
          physics: 5,
          chemistry: 5,
          biology: 5,
          socialScience: 5,
          rights: 5,
          history: 5,
          english: 5,
          german: 5,
          art: 5,
          work: 5,
          religion: 5,
          training: 5,
          sambo: 5,
          judo: 5,
          shooting: 5,
          sledding: 5
        },
        {
          name: 'Дацюк П.А.',
          russian: 4,
          math: 4,
          geometry: 4,
          physics: 4,
          chemistry: 4,
          biology: 5,
          socialScience: 5,
          rights: 5,
          history: 5,
          english: 5,
          german: 4,
          art: 4,
          work: 4,
          religion: 5,
          training: 4,
          sambo: 4,
          judo: 5,
          shooting: 5,
          sledding: 4
        },
        {
          name: 'Кросби С.А.',
          russian: 5,
          math: 5,
          geometry: 5,
          physics: 5,
          chemistry: 5,
          biology: 5,
          socialScience: 5,
          rights: 5,
          history: 5,
          english: 5,
          german: 5,
          art: 5,
          work: 5,
          religion: 5,
          training: 5,
          sambo: 5,
          judo: 5,
          shooting: 5,
          sledding: 5
        },
        {
          name: 'Буре П.А.',
          russian: 10,
          math: 10,
          geometry: 10,
          physics: 10,
          chemistry: 10,
          biology: 10,
          socialScience: 10,
          rights: 10,
          history: 10,
          english: 10,
          german: 10,
          art: 10,
          work: 10,
          religion: 10,
          training: 10,
          sambo: 10,
          judo: 10,
          shooting: 10,
          sledding: 10
        },
        {
          name: 'Самсонов А.А.',
          russian: 3,
          math: 3,
          geometry: 3,
          physics: 3,
          chemistry: 3,
          biology: 3,
          socialScience: 3,
          rights: 3,
          history: 3,
          english: 3,
          german: 3,
          art: 3,
          work: 3,
          religion: 3,
          training: 3,
          sambo: 3,
          judo: 3,
          shooting: 3,
          sledding: 3
        }
      ]
    }
  }
}
</script>

<style>

</style>
